SITE_BASE_TITLE = 'App'
SITE_KEYWORDS = ''
SITE_DESCRIPTION = ''
SITE_DOMAIN = ''

SITE_GOOGLE_ANALYTICS = ''

TWITTER_NAME = 'digitisedlipstk'
GOOGLE_PLUS_NAME = 'kirstywilliams2013'
FACEBOOK_NAME = 'kirstypageone'

APP_NAME = 'App'
APP_SLOGAN = 'Hola!'
BRAND_COLOR = '#ED0F5A'
