default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails4-base_development
  username: rails4_base
  password: 

test:
  <<: *default
  database: rails4-base_test
  username: rails4_base
  password: 

production:
  <<: *default
  database: rails4-base_production
  password: <%= ENV['RAILS4-BASE_DATABASE_PASSWORD'] %>
