# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a82fb3ff5f3725c6fff8084a714965c25d32307902a80330c295a000ce528880d0cfe720fb741a68d5cac3dd27bb84bbeac9e69fbff5192733377633da26a1c

test:
  secret_key_base: a17588a5f0245883fee868fbdad2d1c605fa84b2bb3f35cd137c5a7b13d8b55e3c7805a3d33031ef6f45bcbeba24156becf683d542d5991df508214f8383ec72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
